webtalk_init -webtalk_dir D:/ESCOM/ARQUITECTURA/Practica12/registro/registro.sim/sim_1/behav/xsim/xsim.dir/tb_arreglo_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed May 27 23:45:16 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "a5c89b0d-879c-4196-9026-ad5747f8075f" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "ab296696bdf446d8b0ae30f6b6f0424c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "40" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx  " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2096 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "10.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "6859990 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "2.45_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "13928_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3575577435 -regid "" -xml D:/ESCOM/ARQUITECTURA/Practica12/registro/registro.sim/sim_1/behav/xsim/xsim.dir/tb_arreglo_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/ESCOM/ARQUITECTURA/Practica12/registro/registro.sim/sim_1/behav/xsim/xsim.dir/tb_arreglo_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/ESCOM/ARQUITECTURA/Practica12/registro/registro.sim/sim_1/behav/xsim/xsim.dir/tb_arreglo_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
