@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Tue Jun 30 16:35:33 -0500 2020
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto 3d1a346d8d044c7686fe4d534f5d5e9d --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot TBUC_behav xil_defaultlib.TBUC -log elaborate.log"
call xelab  -wto 3d1a346d8d044c7686fe4d534f5d5e9d --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot TBUC_behav xil_defaultlib.TBUC -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
